config/routes.rb
Rails.application.routes.draw do
  resources :parts do
    collection do
      get 'search'
    end
  end
  resources :cars do
    collection do
      get 'search'
    end
  end
  resources :makes do
  collection do
    get 'search'
  end
end
  resources :countries do
    collection do
      get 'search'
    end
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/make.rb
class Make < ApplicationRecord
  belongs_to :country
  has_many :cars
  validates :name, :country_id, presence: true
end

app/controllers/makes_controller.rb
class MakesController < ApplicationController
  before_action :set_make, only: [:show, :edit, :update, :destroy]

  # GET /makes
  # GET /makes.json
  def index
    @makes = Make.all
  end

  # GET /makes/1
  # GET /makes/1.json
  def show
  end

  # GET /makes/new
  def new
    @make = Make.new
  end

  # GET /makes/1/edit
  def edit
  end

  # POST /makes
  # POST /makes.json
  def create
    @make = Make.new(make_params)

    respond_to do |format|
      if @make.save
        format.html { redirect_to @make, notice: 'Make was successfully created.' }
        format.json { render :show, status: :created, location: @make }
      else
        format.html { render :new }
        format.json { render json: @make.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /makes/1
  # PATCH/PUT /makes/1.json
  def update
    respond_to do |format|
      if @make.update(make_params)
        format.html { redirect_to @make, notice: 'Make was successfully updated.' }
        format.json { render :show, status: :ok, location: @make }
      else
        format.html { render :edit }
        format.json { render json: @make.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /makes/1
  # DELETE /makes/1.json
  def destroy
    @make.destroy
    respond_to do |format|
      format.html { redirect_to makes_url, notice: 'Make was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def search
    @makes = Make.where("name like ?", "%#{params[:query]}%")
    render :index
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_make
      @make = Make.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def make_params
      params.require(:make).permit(:name, :country_id)
    end
end

app/helpers/makes_helper.rb
module MakesHelper
end

app/views/makes/_form.html.erb
<%= form_with(model: make, local: true) do |form| %>
  <% if make.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(make.errors.count, "error") %> prohibited this make from being saved:</h2>

      <ul>
      <% make.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :country_id %>
    <%= form.collection_select :country_id, Country.all, :id, :name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/makes/edit.html.erb
<h1>Editing Make</h1>

<%= render 'form', make: @make %>

<%= link_to 'Show', @make %> |
<%= link_to 'Back', makes_path %>

app/views/makes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Makes</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Country</th>
      <th colspan="3">
        <%= form_tag(search_cars_url, method: "get") do %>
          <%= label_tag(:query, "Search for:") %>
          <%= text_field_tag(:query) %>
          <%= submit_tag("Search") %>
        <% end %>
      </th>
    </tr>
  </thead>

  <tbody>
    <% @makes.each do |make| %>
      <tr>
        <td><%= make.name %></td>
        <td><%= make.country.name %></td>
        <td><%= link_to 'Show', make %></td>
        <td><%= link_to 'Edit', edit_make_path(make) %></td>
        <td><%= link_to 'Destroy', make, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Make', new_make_path %>

app/views/makes/new.html.erb
<h1>New Make</h1>

<%= render 'form', make: @make %>

<%= link_to 'Back', makes_path %>

app/views/makes/show.html.erb
<p id="notice"><%= notice %></p>

<table>
  <thead>
  <tr>
    <th>Name:</th>
    <td><%= @make.name %></td>
    <th>Models</th>
  </tr>
  </thead>

  <tbody>
  <tr>
    <td></td>
    <td></td>
    <td>
      <ol>
        <% @make.cars.each do |car| %>
          <li> <%= car.name %>
        <% end %>
      </ol>
    </td>
  </tr>
  </tbody>
</table>

<%= link_to 'Edit', edit_make_path(@make) %> |
<%= link_to 'Back', makes_path %>